[package]
name = "daw-out"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git",  rev = "7eee0b032e34e2cd8a7a9965dce97b8aa503b20e" }
# nih_plug = { path = "../nih_plug" }
rosc = "0.7.0"
crossbeam-channel = "0.5.4"
parking_lot = "0.12.0"

[workspace]
members = ["xtask"]