name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # This otherwise gets run under dash which does not support brace expansion
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        include:
          - { name: linux,       os: ubuntu-latest }
          - { name: windows,      os: windows-latest }
    name: Build/Publish
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all git history
        run: git fetch --force --prune --tags --unshallow

      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl-dev libjack-dev libxcb1-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb-dri2-0-dev libx11-xcb-dev

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true

      - name: Parse Version
        if: startsWith(github.ref, 'refs/tags/')
        uses: olegtarasov/get-tag@v2.1
        id: tag_version

      - name: Set Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cargo install cargo-edit
          cargo set-version $GIT_TAG_NAME

      - name: Build
        run: cargo xtask bundle daw-out --release

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/bundled/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
